[package]
name = "edr-agent-common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# We need serde only for the User Space side
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
user = ["serde"]
kernel = []